obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.55

#inflation_radius: 0.35

#---standard pioneer footprint---

#---(in inches)---
#footprint: [ [10, -2], [7, -2], [7, -7], [-7.5, -7], [-10, 0], [-7.5, 7], [7, 7], [7, 2], [10, 2] ]

#---(in meters)---
footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

transform_tolerance: 0.3
map_type: costmap

observation_sources: front_laser

front_laser: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: scan_front, marking: true, clearing: true, expected_update_rate: 0.2}
#front_laser: {sensor_frame: base_laser_front, data_type: LaserScan, topic: scan_front, marking: true, clearing: true, expected_update_rate: 0.2}
