obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.55

#---(in meters)---
footprint: [ [0.1, -0.18], [0.1, 0.18], [-0.1, 0.18], [-0.1, -0.18] ]

transform_tolerance: 0.3
map_type: costmap
map_topic: map

observation_sources: front_laser back_laser

front_laser: {
    sensor_frame: base_laser_front_link, 
    data_type: LaserScan, 
    topic: scan_front, 
    marking: true, 
    clearing: true, 
    expected_update_rate: 0.2}

back_laser: {
    sensor_frame: base_laser_back_link, 
    data_type: LaserScan, 
    topic: scan_back, 
    marking: true, 
    clearing: true, 
    expected_update_rate: 0.2}