gazebo_ros_control/pid_gains:
  tray_joint: {p: 1.0, i: 0.0, d: 1.0}
  neck_lower_joint: {p: 1.0, i: 0.0, d: 1.0}
  neck_upper_joint: {p: 1.0, i: 0.0, d: 1.0}
  head_pan_joint: {p: 1.0, i: 0.0, d: 1.0}
  head_tilt_joint: {p: 1.0, i: 0.0, d: 1.0}

tray_controller:
  type: effort_controllers/JointPositionController
  joint: tray_joint
  pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
neck_lower_controller:
  type: effort_controllers/JointPositionController
  joint: neck_lower_joint
  pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
neck_upper_controller:
  type: effort_controllers/JointPositionController
  joint: neck_upper_joint
  pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
head_pan_controller:
  type: effort_controllers/JointPositionController
  joint: head_pan_joint
  pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
head_tilt_controller:
  type: effort_controllers/JointPositionController
  joint: head_tilt_joint
  pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50